// Generated by winograd_constants.py — DO NOT EDIT BY HAND.
// PFA Winograd butterfly constants, 17 sig digits (double round-trip).
#pragma once

// --- Radix-3 (fft-pfa.md §4) ---
constexpr double W3_C              = -0.5;  // cos(2π/3) = -1/2  (exact)
constexpr double W3_S              = 0.86602540378443865;  // sin(2π/3) = √3/2

// --- Radix-5 Winograd (5 real mults, 17 real adds) ---
constexpr double W5_CP             = -0.25;  // (cos 2π/5 + cos 4π/5)/2 = -1/4 (exact)
constexpr double W5_CM             = 0.55901699437494742;  // (cos 2π/5 − cos 4π/5)/2 = √5/4
constexpr double W5_S1             = 0.95105651629515357;  // sin 2π/5
constexpr double W5_S1pS2          = 1.5388417685876267;  // sin 2π/5 + sin 4π/5
constexpr double W5_S2mS1          = -0.36327126400268044;  // sin 4π/5 − sin 2π/5

// --- Radix-7 direct form (18 real mults, ~32 adds) ---
constexpr double W7_C1             = 0.62348980185873353;  // cos 2π·1/7
constexpr double W7_C2             = -0.2225209339563144;  // cos 2π·2/7
constexpr double W7_C3             = -0.90096886790241913;  // cos 2π·3/7
constexpr double W7_S1             = 0.78183148246802981;  // sin 2π·1/7
constexpr double W7_S2             = 0.97492791218182361;  // sin 2π·2/7
constexpr double W7_S3             = 0.43388373911755812;  // sin 2π·3/7

// --- ω_M^k = exp(-2π·i·k/M) tables for PFA cross-pair pointwise dispatch ---
constexpr double W3_RE[3] = {
    1.0, -0.5, -0.5
};
constexpr double W3_IM[3] = {
    0.0, -0.86602540378443865, 0.86602540378443865
};
constexpr double W5_RE[5] = {
    1.0, 0.30901699437494742, -0.80901699437494742, -0.80901699437494742, 0.30901699437494742
};
constexpr double W5_IM[5] = {
    0.0, -0.95105651629515357, -0.58778525229247313, 0.58778525229247313, 0.95105651629515357
};
constexpr double W7_RE[7] = {
    1.0, 0.62348980185873353, -0.2225209339563144, -0.90096886790241913, -0.90096886790241913, -0.2225209339563144, 0.62348980185873353
};
constexpr double W7_IM[7] = {
    0.0, -0.78183148246802981, -0.97492791218182361, -0.43388373911755812, 0.43388373911755812, 0.97492791218182361, 0.78183148246802981
};
